repos:
  - repo: https://github.com/psf/black
    rev: "23.9.1"
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        additional_dependencies: [tomli]
        args:
          - --black
          - --in-place
          - --config=./pyproject.toml

  - repo: https://github.com/adamchainz/blacken-docs
    rev: "1.16.0"
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black

  - repo: https://github.com/finsberg/clang-format-docs
    rev: v0.2.1
    hooks:
      - id: clang-format-docs
        additional_dependencies:
          - clang-format==14.0.6
        args:
          - --style=file:.clang-format

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.3"
    hooks:
      - id: prettier

  - repo: https://github.com/frostming/pofmt
    rev: "0.4.0"
    hooks:
      - id: pofmt
        additional_dependencies: ["pangu"]

  - repo: https://github.com/pycqa/isort
    rev: "5.12.0"
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.5.1"
    hooks:
      - id: mypy
        files: ^src/

  - repo: https://github.com/hakancelikdev/unimport
    rev: "1.0.0"
    hooks:
      - id: unimport
        args:
          - --include=src
