baseURL: "https://abqpy.com/"
languageCode: "en-us"
title: "abqpy"
theme: scientific-python-hugo-theme
relativeURLs: true
disableKinds: ["term", "taxonomy"]

markup:
  highlight:
    noClasses: false

params:
  description: abqpy documentation
  images:
    - /images/logo.svg
  navbarlogo:
    image: logo.svg
    text: abqpy documentation
    link: /
  hero:
    title: ABQPY
    subtitle: Type Hints for Abaqus/Python Scripting
    buttontext: Getting Started
    buttonlink: /getstart/
    image: logo.svg
  navbar:
    - title: Getting Started
      url: /getstart/
    - title: Documentation
      url: https://docs.abqpy.com
      is_external: true
    - title: GitHub
      url: https://github.com/haiiliin/abqpy/
      is_external: true
    - title: PyPI
      url: https://pypi.org/project/abqpy/
      is_external: true
    - title: Anaconda
      url: https://anaconda.org/haiiliin/abqpy/
      is_external: true
    - title: Read the Docs
      url: https://readthedocs.org/projects/abqpy/
      is_external: true
  keyfeatures:
    features:
      - title: Full Abaqus/Python APIs Supported
        text: The abqpy package supports almost all the Abaqus/Python APIs, and provides type hints for them, 
              which can be used by IDEs to provide better code completion and type checking.
      - title: Easy to Use
        text: The abqpy package is easy to use and can be installed via pip, conda, or from source.
              You can run your Abaqus/Python scripts with python directly even without opening Abaqus/CAE.
      - title: Easy to Interact with Abaqus/CAE
        text: The abqpy package provides a simple way to interact with Abaqus/CAE, You can run your Abaqus/Python 
              scripts with python directly even without opening Abaqus/CAE.
  footer:
    logo: logo.svg
    socialmediatitle: ""
    socialmedia:
      - link: https://github.com/haiiliin/abqpy/
        icon: github
      - link: mailto:hailin.wang@connect.polyu.hk
        icon: mail
      - link: https://twitter.com/haiiliin
        icon: twitter

    quicklinks:
      column1:
        title: ""
        links:
          - text: Getting Started
            link: /getstart/
          - text: Documentation
            link: https://docs.abqpy.com
          - text: Tutorials
            link: https://docs.abqpy.com/en/latest/tutorials.html
          - text: Templates
            link: https://docs.abqpy.com/en/latest/templates.html
          - text: User's Guide
            link: https://abqpy.readthedocs.io/en/latest/
          - text: API Summary
            link: https://abqpy.readthedocs.io/en/latest/api.html
          - text: API Reference
            link: https://abqpy.readthedocs.io/en/latest/api_reference.html
      column2:
        links:
          - text: GitHub
            link: https://github.com/haiiliin/abqpy/
          - text: PyPI
            link: https://pypi.org/project/abqpy/
          - text: Anaconda
            link: https://anaconda.org/haiiliin/abqpy/
          - text: Read the Docs
            link: https://readthedocs.org/projects/abqpy/
      column3:
        links:
          - text: Abaqus Documentation
            link: https://help.3ds.com/2022/English/DSSIMULIA_Established/SIMULIA_Established_FrontmatterMap/sim-r-DSDocAbaqus.htm
          - text: Scripting User's Guide
            link: https://help.3ds.com/2022/English/DSSIMULIA_Established/SIMACAECMDRefMap/simacmd-c-ov.htm
          - text: Scripting Reference
            link: https://help.3ds.com/2022/English/DSSIMULIA_Established/SIMACAEKERRefMap/simaker-c-ov.htm
