name: docs translations

on:
  pull_request:
    branches:
    - main
    - 20**
    types: [opened, reopened, synchronize, labeled]
    paths:
    - 'docs/source/locales/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs-test:
    if: ${{ github.base_ref == 'main' || contains(github.event.pull_request.labels.*.name, 'conflicts') || contains(github.event.pull_request.labels.*.name, 'docs-test') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: ['zh_CN']
    steps:
    - uses: actions/setup-python@v2
    - uses: actions/checkout@v3.1.0
      with:
        fetch-depth: 0
    - name: Installing the library
      shell: bash -l {0}
      run: |
        pip install .
        pip install -r docs/requirements.txt
    - name: Build the documentation
      shell: bash -l {0}
      run: |
        sphinx-build -b html -D language=${{ matrix.language }} docs/source docs/build/${{ matrix.language }}/html/pr-${{ github.event.number }}
        touch  docs/build/${{ matrix.language }}/html/pr-${{ github.event.number }}/.nojekyll
        rm -rf docs/build/${{ matrix.language }}/html/pr-${{ github.event.number }}/.doctrees
    - name: Create pull request
      if: ${{ contains(github.event.pull_request.labels.*.name, 'docs-preview') }}
      uses: haiiliin/action-pull-request-another-repo@v1.0.3
      env:
        API_TOKEN_GITHUB: ${{ secrets.CREATE_PULL_REQUEST }}
      with:
        source_folder: docs/build/${{ matrix.language }}/html/pr-${{ github.event.number }}
        destination_repo: 'haiiliin/devdocs.abqpy.com'
        destination_folder: '${{ matrix.language }}'
        destination_base_branch: 'main'
        destination_head_branch: 'docs/${{ matrix.language }}/pr-${{ github.event.number }}'
        user_email: '41898282+github-actions[bot]@users.noreply.github.com'
        user_name: 'github-actions[bot]'
        pull_request_reviewers: 'haiiliin'
        title: 'Update docs/${{ matrix.language }}/pr-${{ github.event.number }}'
        body: 'Update docs/${{ matrix.language }}/pr-${{ github.event.number }} from ${{ github.repository }}#${{ github.event.number }}'
    - name: Comment PR
      if: ${{ contains(github.event.pull_request.labels.*.name, 'docs-preview') }}
      uses: Beakyn/gha-comment-pull-request@v1.0.1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        description-message: |
          ----
          # Docs Preview
          The pull request for updating the documentation has been created, after the pull request is merged, the documentation will be updated automatically on https://devdocs.abqpy.com/${{ matrix.language }}/pr-${{ github.event.number }}.
        delete-previous-comment: true
