name: Test docs

on:
  pull_request:
    branches:
    - main
    types: [opened, reopened, synchronize]
    paths:
    - 'src/**'
    - 'docs/source/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: ['en', 'zh_CN']
    steps:
    - uses: actions/setup-python@v2
    - uses: actions/checkout@v3.1.0
    - name: Installing the library
      shell: bash -l {0}
      run: |
        python setup.py install
        pip install -r docs/requirements.txt
    - name: Build the documentation
      shell: bash -l {0}
      run: |
        sphinx-build -b html -D language=${{ matrix.language }} docs/source docs/build/${{ matrix.language }}/html/pr-${{ github.event.number }}
    - uses: benjlevesque/short-sha@v1.2
      if: ${{ contains(github.event.pull_request.labels.*.name, 'docs-preview') }}
      id: short-sha
      with:
        length: 7
    - name: Create pull request
      if: ${{ contains(github.event.pull_request.labels.*.name, 'docs-preview') }}
      uses: paygoc6/action-pull-request-another-repo@v1.0.1
      env:
        API_TOKEN_GITHUB: ${{ secrets.CREATE_PULL_REQUEST }}
      with:
        source_folder: docs/build/${{ matrix.language }}/html/pr-${{ github.event.number }}
        destination_repo: 'haiiliin/docs.abqpy.com'
        destination_folder: '${{ matrix.language }}'
        destination_base_branch: 'main'
        destination_head_branch: 'docs/${{ matrix.language }}/pr-${{ github.event.number }}'
        user_email: '41898282+github-actions[bot]@users.noreply.github.com'
        user_name: 'github-actions[bot]'
        pull_request_reviewers: 'haiiliin'
    - name: Comment PR
      if: ${{ contains(github.event.pull_request.labels.*.name, 'docs-preview') }}
      uses: thollander/actions-comment-pull-request@v1
      with:
        message: |
          This pull request is now in preview on https://docs.abqpy.com/${{ matrix.language }}/pr-${{ github.event.number }}.
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
