name: Upload docs
on:
  push:
    branches:
    - 'main'
    paths:
    - 'src/**'
    - 'docs/source/**'
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: ['en', 'zh_CN']
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y/%m/%d')"
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - uses: actions/checkout@v3.1.0
      with:
        fetch-depth: 0
    - name: Get current version
      id: version
      uses: actions/github-script@v6.3.1
      with:
        script: |
          let value = context.ref.split('/').slice(2).join('/').toLowerCase();
          if (value.startsWith('v')) {value = value.slice(1).split('.')[0]}
          if (value == "main") { value = "dev"; }
          core.setOutput('value', value)
    - run: echo "version ${{ steps.version.outputs.value }}"
    - name: Build and Commit
      id: build
      run: |
        pip install -r docs/requirements.txt
        pip install .
        sphinx-build -b html -D language=${{ matrix.language }} docs/source docs/build/html/${{ matrix.language }}/${{ steps.version.outputs.value }}
        touch "docs/build/html/${{ matrix.language }}/${{ steps.version.outputs.value }}/.nojekyll"
        rm -rf docs/build/html/${{ matrix.language }}/${{ steps.version.outputs.value }}/.doctrees
    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 7
    - name: Create pull request
      uses: haiiliin/action-pull-request-another-repo@v1.0.3
      env:
        API_TOKEN_GITHUB: ${{ secrets.CREATE_PULL_REQUEST }}
      with:
        source_folder: docs/build/html/${{ matrix.language }}/${{ steps.version.outputs.value }}
        destination_repo: 'haiiliin/docs.abqpy.com'
        destination_folder: '${{ matrix.language }}'
        destination_base_branch: 'main'
        destination_head_branch: 'docs/${{ matrix.language }}/${{ steps.version.outputs.value }}-${{ steps.short-sha.outputs.sha }}'
        user_email: '41898282+github-actions[bot]@users.noreply.github.com'
        user_name: 'github-actions[bot]'
        pull_request_reviewers: 'haiiliin'
        title: 'Update docs/${{ matrix.language }}/${{ steps.version.outputs.value }}-${{ steps.short-sha.outputs.sha }}'
        body: 'Update docs/${{ matrix.language }}/${{ steps.version.outputs.value }}-${{ steps.short-sha.outputs.sha }} by GitHub Action https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
