name: docs-test

on:
  pull_request:
    branches:
    - '20**'
    types: [opened, reopened, synchronize]
    paths:
    - 'src/**'
    - 'docs/source/**'

jobs:
  docs-test:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'conflicts') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: ['en', 'zh_CN']
    steps:
    - uses: actions/setup-python@v2
    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Installing the library
      shell: bash -l {0}
      run: |
        python setup.py install
        pip install -r docs/requirements.txt
    - name: Build the documentation
      shell: bash -l {0}
      run: |
        sphinx-build -b html -D language=${{ matrix.language }} docs/source docs/build/${{ matrix.language }}/html
    - name: Upload the documentation to preview
      if: ${{ contains(github.event.pull_request.labels.*.name, 'docs-preview') && matrix.language == 'en' }}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        directory: docs/build/en/html
