name: Add Release News

on:
  workflow_dispatch:
  inputs:
    version:
      type: string
      description: Version number
      required: true

jobs:
  release-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Add Release News
        run: |
          python .github/create-release-news.py ${{ github.event.inputs.version }}
      - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: Add Release News by GitHub Action https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        body: |
          This is an automated pull request to add release news by GitHub Action [${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).
        author: haiiliin <hailin.wang@connect.polyu.hk>
        title: Add Release News (${{ steps.date.outputs.date }})
        labels: release
        branch: "abqpy.com"
        token: ${{ secrets.ACTION_TOKEN }}
