name: Release Drafter

on:
  push:
    branches: ["20**"]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        id: release_drafter
        with:
          config-name: release-drafter-2017.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Tag the next version
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git tag -a ${{ steps.release_drafter.outputs.tag_name }} -m "Release ${{ steps.release_drafter.outputs.tag_name }}"
      - name: Build package
        run: |
          python -m build
          cd wrapper && python -m build
      - name: Upload binaries to release
        run: |
          gh release upload --clobber ${{ env.VERSION }} dist/*.tar.gz dist/*.whl
          gh release upload --clobber ${{ env.VERSION }} wrapper/dist/*.tar.gz wrapper/dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.release_drafter.outputs.tag_name }}
