name: Update Release
on:
  workflow_dispatch:
    inputs:
      update:
        type: boolean
        description: Update version number in the repo or not
        required: true
        default: true

jobs:
  update-release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch: ["main", "2016", "2017", "2018", "2019", "2020", "2021", "2022"]

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y/%m/%d')"
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}
          fetch-depth: 0
      - name: Determine Release Drafter Suffix
        uses: haya14busa/action-cond@v1
        id: drafter_suffix
        with:
          cond: ${{ matrix.branch == 'main' }}
          if_true: "2022"  # string value
          if_false: ${{ matrix.branch }} # string value
      - name: Update release drafter
        id: create_release_drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-${{ steps.drafter_suffix.outputs.value }}.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update suggested version for ${{ matrix.branch }}
        if: ${{ inputs.update }}
        run: |
          echo "tag = ${{ steps.create_release_drafter.outputs.tag_name }}"
          python ".github/update-suggested-version.py" "${{ steps.create_release_drafter.outputs.tag_name }}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update release version by GitHub Action https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          body: |
            This is an automated pull request to update the release version by GitHub Action [${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          title: "[release]: Update release version (${{ steps.date.outputs.date }})"
          labels: release, ${{ matrix.branch }}, disable-auto-merge
          branch: update-version-to-${{ matrix.branch }}
          token: ${{ secrets.ACTION_TOKEN }}
