name: Update suggested version

on:
  workflow_dispatch:

jobs:
  update-release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["2016", "2017", "2018", "2019", "2020", "2021", "2022"]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Update release drafter
        id: create_release_drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-v${{ matrix.version }}.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update suggested version and create commit for 'V20**'
        run: |
          echo "tag = ${{ steps.create_release_drafter.outputs.tag_name }}"
          git branch -a
          git checkout V${{ matrix.version }}  # attach this repo
          git config --global user.email "hailin.wang@connect.polyu.hk"
          git config --global user.name "abqpy-bot"
          python ".github/update-suggested-version.py" "${{ steps.create_release_drafter.outputs.tag_name }}"
          git add .
          git commit -m "Update version by GHA https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      - name: Push to the protected branch 'V20**'
        if: ${{ matrix.branch != 'main' }}
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
          branch: V${{ matrix.version }}
  
  update-version-on-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Update release drafter
        id: create_release_drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-v2022.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update suggested version and create commit for 'main'
        run: |
          echo "tag = ${{ steps.create_release_drafter.outputs.tag_name }}"
          git branch -a
          git checkout main  # attach this repo
          git config --global user.email "hailin.wang@connect.polyu.hk"
          git config --global user.name "abqpy-bot"
          python ".github/update-suggested-version.py" "${{ steps.create_release_drafter.outputs.tag_name }}"
          git add .
          git commit -m "Update version by GHA https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      - name: Push to the protected branch 'main'
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
          branch: main
