name: update-translations

on:
  schedule:
    - cron: "0 0 * * *" #runs at 00:00 UTC everyday
  workflow_dispatch:

jobs:
  update-translations:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch: [main, V2022, V2021, V2020, V2019, V2018, V2017, V2016]

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ matrix.branch }}
        fetch-depth: 0
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Check Python version
      run: python --version
    - name: Install dependencies
      run: |
        pip install -r ./docs/requirements.txt
        python setup.py install
    - name: Update translations
      run: sh ./docs/source/locales/update.sh
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      commit-message: Update translations by GHA https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      author: haiiliin <hailin.wang@connect.polyu.hk>
      labels: translation
      branch: ${{ matrix.branch }}
